$ErrorActionPreference = "Stop"
Set-Location -LiteralPath "C:\Users\Varnit Asthana\OneDrive\Desktop\ecommerce-web-app"

if (-not (Test-Path -LiteralPath ".git")) {
  Write-Error "Not a git repository"
  exit 1
}

$files = @(
  "ARCHITECTURE.md",
  "CI-CD.md",
  "COMPLETION_REPORT.md",
  "DATA_ARCHITECTURE.md",
  "DEPLOYMENT.md",
  "FINAL_PRODUCTION_CHECKLIST.md",
  "PRODUCTION_READY.md",
  "PROJECT_AUDIT.md",
  "SECURITY.md",
  "TESTING.md",
  "UPGRADE_SUMMARY.md",
  ".dockerignore",
  ".github/workflows/deploy.yml",
  "Dockerfile",
  "docker-compose.yml",
  "nginx/nginx.conf",
  "scripts/deploy.ps1",
  "scripts/deploy.sh",
  "scripts/verify-deployment.js",
  "client/index.html",
  "client/src/App.css",
  "client/src/App.jsx",
  "client/src/components/Input.css",
  "client/src/components/Toast.css",
  "client/src/context/AuthContext.jsx",
  "client/src/index.css",
  "client/src/main.jsx",
  "client/src/pages/Admin.jsx",
  "client/src/pages/Cart.jsx",
  "client/src/pages/Checkout.jsx",
  "client/src/pages/Home.jsx",
  "client/src/pages/Login.jsx",
  "client/src/pages/OrderConfirmation.jsx",
  "client/src/pages/OrderDetail.jsx",
  "client/src/pages/Orders.jsx",
  "client/src/pages/ProductDetails.jsx",
  "client/src/pages/Products.jsx",
  "client/src/pages/SellerDashboard.jsx",
  "client/src/pages/Support.jsx",
  "client/src/pages/Wishlist.jsx",
  "client/src/pages/Addresses.jsx",
  "client/src/pages/Compare.jsx",
  "client/src/pages/Notifications.jsx",
  "client/src/pages/Returns.jsx",
  "client/src/pages/SellerAnalytics.jsx",
  "client/src/components/Breadcrumb.jsx",
  "client/src/components/CloudinaryUpload.jsx",
  "client/src/components/ErrorBoundary.jsx",
  "client/src/components/MegaMenu.jsx",
  "client/src/components/MobileNav.jsx",
  "client/src/components/OrderTracking.jsx",
  "client/src/components/PriceDropAlert.jsx",
  "client/src/components/QASection.jsx",
  "client/src/components/QuickViewModal.jsx",
  "client/src/components/SearchAutocomplete.jsx",
  "client/src/components/ShareButton.jsx",
  "client/src/components/SizeGuide.jsx",
  "client/src/components/Skeleton.jsx",
  "client/src/services/api.js",
  "client/public/manifest.json",
  "client/public/sw.js",
  "package.json",
  "server/.env.example",
  "server/__tests__/api.test.js",
  "server/config/db.js",
  "server/config/integrations.js",
  "server/config/razorpay.js",
  "server/controllers/adminOrderController.js",
  "server/controllers/authController.js",
  "server/controllers/cartController.js",
  "server/controllers/categoryController.js",
  "server/controllers/compareController.js",
  "server/controllers/couponAdminController.js",
  "server/controllers/couponController.js",
  "server/controllers/notificationController.js",
  "server/controllers/orderController.js",
  "server/controllers/paymentController.js",
  "server/controllers/productController.js",
  "server/controllers/questionController.js",
  "server/controllers/recentlyViewedController.js",
  "server/controllers/returnController.js",
  "server/controllers/sellerAnalyticsController.js",
  "server/controllers/tokenController.js",
  "server/controllers/wishlistController.js",
  "server/middleware/authMiddleware.js",
  "server/models/Cart.js",
  "server/models/Category.js",
  "server/models/Coupon.js",
  "server/models/Notification.js",
  "server/models/Order.js",
  "server/models/Product.js",
  "server/models/Question.js",
  "server/models/Return.js",
  "server/models/User.js",
  "server/models/Wishlist.js",
  "server/package-lock.json",
  "server/package.json",
  "server/routes/adminOrderRoutes.js",
  "server/routes/authRoutes.js",
  "server/routes/cartRoutes.js",
  "server/routes/categoryAdminRoutes.js",
  "server/routes/categoryRoutes.js",
  "server/routes/compareRoutes.js",
  "server/routes/couponAdminRoutes.js",
  "server/routes/couponRoutes.js",
  "server/routes/guestPaymentRoutes.js",
  "server/routes/notificationRoutes.js",
  "server/routes/orderRoutes.js",
  "server/routes/paymentRoutes.js",
  "server/routes/questionRoutes.js",
  "server/routes/returnRoutes.js",
  "server/routes/sellerAnalyticsRoutes.js",
  "server/routes/tokenRoutes.js",
  "server/routes/userRoutes.js",
  "server/routes/wishlistRoutes.js",
  "server/server.js",
  "server/server.production.js",
  "server/services/refundService.js",
  "server/utils/productUtils.js",
  "server/validators/productValidator.js",
  "server/ui-debug-checkout.js"
)

$messages = @(
  "docs: update architecture documentation",
  "docs: update CI-CD documentation",
  "docs: update completion report",
  "docs: update data architecture documentation",
  "docs: update deployment documentation",
  "docs: add final production checklist",
  "docs: add production readiness documentation",
  "docs: update project audit documentation",
  "docs: update security documentation",
  "docs: update testing documentation",
  "docs: update upgrade summary",
  "chore: add docker ignore rules",
  "ci: add deployment workflow",
  "chore: add production Dockerfile",
  "chore: add docker compose configuration",
  "chore: add nginx reverse proxy configuration",
  "chore: add PowerShell deployment script",
  "chore: add bash deployment script",
  "chore: add deployment verification script",
  "chore: update client index html",
  "chore: update client global styles",
  "feat: enhance React app bootstrap and routing",
  "chore: update input component styles",
  "chore: update toast component styles",
  "feat: enhance authentication context",
  "chore: update global CSS variables",
  "chore: update client entry point",
  "feat: enhance admin dashboard page",
  "feat: enhance shopping cart page",
  "feat: enhance checkout page flow",
  "feat: enhance home page experience",
  "feat: enhance login page",
  "feat: enhance order confirmation page",
  "feat: enhance order detail page",
  "feat: enhance orders listing page",
  "feat: enhance product details page",
  "feat: enhance products listing page",
  "feat: enhance seller dashboard page",
  "feat: enhance support page",
  "feat: enhance wishlist page",
  "feat: add addresses page",
  "feat: add product compare page",
  "feat: add notifications page",
  "feat: add returns and refunds page",
  "feat: add seller analytics page",
  "feat: add breadcrumb navigation component",
  "feat: add Cloudinary upload component",
  "feat: add error boundary component",
  "feat: add mega menu navigation component",
  "feat: add mobile navigation component",
  "feat: add order tracking component",
  "feat: add price drop alert component",
  "feat: add Q&A section component",
  "feat: add quick view modal component",
  "feat: add search autocomplete component",
  "feat: add share button component",
  "feat: add size guide component",
  "feat: add skeleton loading component",
  "feat: enhance API service layer",
  "chore: add PWA manifest",
  "chore: add service worker for offline support",
  "chore: update root package.json",
  "chore: update server environment example",
  "test: enhance API test coverage",
  "feat: enhance database connection configuration",
  "feat: enhance external integrations configuration",
  "feat: add Razorpay payment configuration",
  "feat: add admin order controller",
  "feat: enhance authentication controller",
  "feat: add cart controller",
  "feat: add category controller",
  "feat: add product compare controller",
  "feat: add coupon admin controller",
  "feat: add coupon controller",
  "feat: add notification controller",
  "feat: enhance order controller",
  "feat: enhance payment controller",
  "feat: enhance product controller",
  "feat: add question controller",
  "feat: add recently viewed controller",
  "feat: add return controller",
  "feat: add seller analytics controller",
  "feat: add refresh token controller",
  "feat: enhance wishlist controller",
  "feat: enhance auth middleware",
  "feat: add cart model",
  "feat: add category model",
  "feat: add coupon model",
  "feat: add notification model",
  "feat: enhance order model",
  "feat: enhance product model",
  "feat: add question model",
  "feat: add return model",
  "feat: enhance user model",
  "feat: enhance wishlist model",
  "chore: update server package lockfile",
  "chore: update server package.json",
  "feat: add admin order routes",
  "feat: enhance auth routes",
  "feat: add cart routes",
  "feat: add category admin routes",
  "feat: add category routes",
  "feat: add compare routes",
  "feat: add coupon admin routes",
  "feat: add coupon routes",
  "feat: add guest payment routes",
  "feat: add notification routes",
  "feat: enhance order routes",
  "feat: enhance payment routes",
  "feat: add question routes",
  "feat: add return routes",
  "feat: add seller analytics routes",
  "feat: add token routes",
  "feat: add user routes",
  "feat: enhance wishlist routes",
  "feat: enhance Express server configuration",
  "feat: add production server configuration",
  "feat: enhance refund service",
  "feat: enhance product utilities",
  "feat: enhance product validator",
  "chore: add UI debug checkout helper"
)

if ($files.Count -ne $messages.Count) {
  Write-Error "Mismatched file and message counts: files=$($files.Count), messages=$($messages.Count)"
  exit 1
}

$skipped = 0
for ($i = 0; $i -lt $files.Count; $i++) {
  $file = $files[$i]
  $message = $messages[$i]

  if (-not (Test-Path -LiteralPath $file)) {
    Write-Host "[skip] $file does not exist"
    $skipped++
    continue
  }

  git add -- "$file"
  if ($LASTEXITCODE -ne 0) {
    Write-Error "git add failed for $file"
    exit 1
  }

  git commit -m "$message"
  if ($LASTEXITCODE -ne 0) {
    Write-Error "git commit failed for $file"
    exit 1
  }

  Write-Host "[commit] $message"
}

if ($skipped -gt 0) {
  Write-Host "Completed with $skipped skipped files."
} else {
  Write-Host "All commits completed."
}
